# language: java
# jdk: oraclejdk8
# install: true
# script: ./mvnw clean install
# cache:
#   directories:
#   - $HOME/.m2
# jdk:
#   - oraclejdk8
# language: java
# sudo: false
# branches:
#   only:
#   - develop
#   - /^release\/v.*$/
#   - /^hotfix\/v.*$/
# cache:
#   directories:
#     - $HOME/.m2
# jdk:
# - oraclejdk8


language: java
sudo: false
script: mvn clean verify
