language: java
jdk:
  - openjdk8

install: true
script:  ./mvnw verify javadoc:jar@attach-javadocs -B -V

# jobs:
#   include:
#     - stage: Test
#       script: ./mvnw clean test
      
cache:
  directories:
    - $HOME/ .m2
